#!/usr/bin/env bash
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

### Install SBP (simple bash prompt)
if [[ ! -d "$HOME/.sbp" ]]; then
    git clone "https://github.com/brujoand/sbp.git" "$HOME/.sbp"
fi

# Save the existing bashrc file (for Codespaces)
if [[ -n "${CODESPACES:-}" && -e "$HOME/.bashrc" ]]; then
    cp "$HOME/.bashrc" "$HOME/.bashrc_cs"
fi

### Copy dotfiles to home directory
echo "Copying dotfiles to $HOME..."
rsync -a "$DOTFILES_DIR/home/" "$HOME/"

# Merge the bashrc with the pre-existing one (for Codespaces)
if [[ -n "${CODESPACES:-}" && -e "$HOME/.bashrc_cs" ]]; then
    cat "$HOME/.bashrc_cs" >> "$HOME/.bashrc"
fi

if [[ -n "${BP_DEV:-}" ]]; then
    instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
    aws ec2 describe-tags --filters "Name=resource-id,Values=${instance_id}" --query 'Tags [?Key==`custom_tags`].Value' \
        | tr -d '\n[]" ' \
        >> "$HOME/.bpdev_tags"
fi
